-- 🍽️ Pace Restaurant Database Schema (Supabase Postgres)

-- 1. Live Menu Table
CREATE TABLE IF NOT EXISTS "MenuPace" (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price NUMERIC NOT NULL,
    variant TEXT,
    available BOOLEAN DEFAULT true,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Orders Table — order_id generated by DB sequence
CREATE SEQUENCE IF NOT EXISTS pace_order_seq START 1;

CREATE TABLE IF NOT EXISTS "pace_orders" (
    order_id TEXT PRIMARY KEY DEFAULT
        'PACE-' || to_char(now(), 'YYYYMMDD') || '-' ||
        LPAD(nextval('pace_order_seq')::TEXT, 5, '0'),
    session_confirm_key TEXT UNIQUE,   -- Idempotency guard
    customer_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    order_type TEXT NOT NULL,          -- 'Delivery' or 'Takeaway'
    delivery_address TEXT,
    pickup_time TEXT,
    order_items TEXT NOT NULL,
    total_bill NUMERIC NOT NULL,
    subtotal NUMERIC,
    thal_deposit NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'Pending',     -- 'Pending','Confirmed','Dispatched','Cancelled','Expired'
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Customer Profile History
CREATE TABLE IF NOT EXISTS "customer_profiles" (
    phone_number TEXT PRIMARY KEY,
    customer_name TEXT,
    default_address TEXT,
    total_orders INTEGER DEFAULT 0,
    last_order_items TEXT,
    last_ordered_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Admin action audit log
CREATE TABLE IF NOT EXISTS "admin_actions" (
    id BIGSERIAL PRIMARY KEY,
    actor_jid TEXT NOT NULL,
    command TEXT NOT NULL,
    target TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Dead-letter log for exhausted external-call retries
CREATE TABLE IF NOT EXISTS "failed_dispatches" (
    id BIGSERIAL PRIMARY KEY,
    kind TEXT NOT NULL,               -- 'notify_admin' | 'notify_kitchen' | 'whisper' | 'nightly_report'
    payload JSONB NOT NULL,
    error TEXT NOT NULL,
    attempts INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    resolved BOOLEAN DEFAULT false
);

-- ── Row-Level Security (RLS) ──
ALTER TABLE "MenuPace" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pace_orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "customer_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "admin_actions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "failed_dispatches" ENABLE ROW LEVEL SECURITY;

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_pace_orders_phone ON "pace_orders" (phone_number);
CREATE INDEX IF NOT EXISTS idx_pace_orders_status ON "pace_orders" (status);
CREATE INDEX IF NOT EXISTS idx_pace_orders_created_at ON "pace_orders" (created_at);
CREATE INDEX IF NOT EXISTS idx_menu_pace_category ON "MenuPace" (category);
CREATE INDEX IF NOT EXISTS idx_failed_dispatches_resolved ON "failed_dispatches" (resolved);
